name: bayleef-nau
channels:
  - anaconda
  - usgs-astrogeology
  - conda-forge
  - defaults
  - default
dependencies:
  - geoalchemy2
  - pyyaml
  - requests
  - python[version='>=3']
  - click
  - pysis
  - autocnet
  - mock
  - pytest
  - geopandas
  - pywget
  - matplotlib
  - plio[version='>=1.1.0']
  - usgs-astrogeology/label/dev::usgscsm
  - pip
  - sqlalchemy
  - csmapi
  - knoten
  - plurmy
  - ipykernel
  - pyproj
  - opencv[version='<=3.5']
  - cyvlfeat
  - shapely
  - networkx
  - scikit-image
  - dill
  - imageio
  - pillow
  - numpy
  - sqlalchemy-utils
  - coveralls
  - psycopg2
  - vlfeat
  - pytest-cov
  - scipy[version='<=1.2.1']
  - jupyter
  - ncurses
  - seaborn

