name: autocnet
channels:
  - usgs-astrogeology
  - conda-forge
  - menpo
  - anaconda
  - defaults
dependencies:
  - matplotlib=2.2.2
  - pywget=3.2
  - affine=2.2.1
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - attrs=18.2.0
  - automat=0.7.0
  - backcall=0.1.0
  - blas=1.1
  - bleach=2.1.4
  - boost-cpp=1.67.0
  - bzip2=1.0.6
  - ca-certificates=2018.8.24
  - cairo=1.14.12
  - certifi=2018.8.24
  - cffi=1.11.5
  - click=6.7
  - click-plugins=1.0.3
  - cligj=0.4.0
  - cloudpickle=0.5.5
  - constantly=15.1.0
  - cryptography=2.3.1
  - cryptography-vectors=2.3.1
  - curl=7.61.0
  - cycler=0.10.0
  - cython=0.28.5
  - dask-core=0.19.1
  - dbus=1.13.0
  - decorator=4.3.0
  - descartes=1.1.0
  - dill=0.2.8.2
  - entrypoints=0.2.3
  - expat=2.2.5
  - ffmpeg=4.0.2
  - fiona=1.7.13
  - fontconfig=2.13.0
  - freetype=2.8.1
  - freexl=1.0.5
  - gdal=2.2.4
  - geoalchemy2=0.5.0
  - geopandas=0.4.0
  - geos=3.6.2
  - geotiff=1.4.2
  - gettext=0.19.8.1
  - giflib=5.1.4
  - glib=2.55.0
  - gmp=6.1.2
  - graphite2=1.3.12
  - h5py=2.8.0
  - harfbuzz=1.8.5
  - hdf4=4.2.13
  - hdf5=1.10.2
  - html5lib=1.0.1
  - hyperlink=17.3.1
  - icu=58.2
  - idna=2.7
  - imageio=2.3.0
  - incremental=17.5.0
  - ipykernel=4.9.0
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.1
  - jasper=1.900.1
  - jedi=0.12.1
  - jinja2=2.10
  - jpeg=9c
  - json-c=0.12.1
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - kealib=1.4.9
  - kiwisolver=1.0.1
  - krb5=1.14.6
  - libdap4=3.19.1
  - libffi=3.2.1
  - libgdal=2.2.4
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.35
  - libpq=9.6.3
  - libprotobuf=3.6.0
  - libsodium=1.0.16
  - libspatialindex=1.8.5
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libuuid=2.32.1
  - libwebp=0.5.2
  - libxcb=1.13
  - libxml2=2.9.8
  - markupsafe=1.0
  - mistune=0.8.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - munch=2.3.2
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - nettle=3.3
  - networkx=2.1
  - notebook=5.6.0
  - numexpr=2.6.6
  - numpy=1.13.3
  - olefile=0.46
  - openblas=0.2.20
  - opencv=3.4.3
  - openh264=1.7.0
  - openjpeg=2.3.0
  - openssl=1.0.2p
  - pandas=0.23.4
  - pandoc=2.2.2
  - pandocfilters=1.4.2
  - parso=0.3.1
  - patsy=0.5.0
  - pcre=8.41
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pillow=5.2.0
  - pip=18.0
  - pixman=0.34.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - proj4=4.9.3
  - prometheus_client=0.3.0
  - prompt_toolkit=1.0.15
  - protobuf=3.6.0
  - psycopg2=2.7.5
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pvl=0.3.0
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.1
  - pycparser=2.18
  - pygments=2.2.0
  - pyhamcrest=1.9.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyproj=1.9.5.1
  - pyqt=5.6.0
  - pysal=1.14.4.post2
  - python=3.6.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - pywavelets=1.0.0
  - pyyaml=3.13
  - pyzmq=17.1.2
  - qt=5.6.2
  - qtconsole=4.4.1
  - readline=7.0
  - rtree=0.8.3
  - scikit-image=0.14.0
  - scipy=1.1.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - service_identity=17.0.0
  - setuptools=40.2.0
  - shapely=1.6.4
  - simplegeneric=0.8.1
  - sip=4.18.1
  - six=1.11.0
  - sqlalchemy=1.2.11
  - sqlite=3.24.0
  - statsmodels=0.9.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=5.1
  - traitlets=4.3.2
  - twisted=18.7.0
  - vlfeat=0.9.20
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.31.1
  - widgetsnbextension=3.4.1
  - xerces-c=3.2.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.2
  - xorg-libx11=1.6.6
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xorg-libxext=1.3.3
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11
  - zope.interface=4.5.0
  - cyvlfeat=0.4.6
  - libcsm
  - plio
  - csmapi
  - pip
  - pip:
    - pysis
